### PR TITLE
Merging pfn/keepass/1.8.4.1 into trusty

### PR DESCRIPTION
**Pull request by synchrone**
`git merge 1.8.4.1` on top of dlech/trusty. Merge conflict in `KeePassHttp.csproj` resolved by removing `<TargetFrameworkVersion>`

### CODE REVIEW

**Comment by dlech** [comment]
Thanks! I suppose you might like it if I published this to the ppa as well. :wink:

**Comment by dlech** [comment]
I have published this at `ppa:dlech/keepass2-plugins-beta`. Please test. If it works, I will publish it to `ppa:dlech/keepass2-plugins` as well.

**Comment by synchrone** [comment]
LGTM :+1:

**Comment by dlech** [comment]
This is published in `ppa:dlech/keepass2-plugins` now.

**Pull request merged**
